name: Main CI

on:
  push:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      FAUNA_SECRET_KEY: ${{ secrets.FAUNA_SECRET_KEY }}

    strategy:
      matrix:
        node-version: [18.x]  # You can define multiple Node.js versions if needed

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: npm install

    - name: Install Fauna Shell 
      run : npm install -g fauna-shell@beta
    
    - name: Create .fauna-shell config
      run: echo -e "default=cloud-global\n\n[endpoint.cloud-global]\nsecret=${{ secrets.FAUNA_SHELL_SECRET_KEY }}" > ~/.fauna-shell

    - name: Push schema to Test Database
      run: fauna schema push --stack testd --force

    - name: Set environment variable
      run: export FAUNA_SECRET_KEY=${{ secrets.FAUNA_SECRET_KEY }}

    - name: Run tests
      run: npm test
    
    - name: Reset Test Database
      run: fauna delete --stack testd --dir=./cleanup/ --force

      env:
        FAUNA_SHELL_SECRET_KEY: ${{ secrets.FAUNA_SHELL_SECRET_KEY }}
